(ns hive-carto-flow-vim.pack
  "Keep the provisioned client runtime current.

   hive-addon's runtime provisioner (hive-addon.runtime.boundary/provisioner)
   installs this addon's `:addon/runtime` by copying the source directory (the
   `:carto-flow.vim/plugin-dir` hook, the extracted Vim runtime) into
   `hive-addon.runtime.plan/install-dir`, e.g.
   ~/.vim/pack/hive/start/hive-carto-flow, and writing a generated loader
   (plugin/zz_hive_runtime.vim) there. It records what it installed as the
   RuntimeDecls per addon id (its `:installed` fn), and derives every path from
   a decl, a client profile and a home. That happens only at provisioning, so
   a plugin edited afterwards leaves every NEW Vim on the old copy.

   `refresh!` reuses the same record and the same path derivation: for each
   installed decl it finds the install, and when it exists and carries the
   loader the provisioner generated for that runtime, rewrites the files of
   the source directory whose content differs, each atomically. It never
   creates an install, never touches a path outside the source tree (so files
   the provisioner did not copy are left alone), never rewrites the loader,
   and stops as soon as the install disappears (a concurrent :deprovision)."
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.string :as str]
            [hive-addon.runtime.plan :as plan])
  (:import (java.io File)
           (java.nio.file Files StandardCopyOption)))

(def manifest-resource "META-INF/hive-addons/hive-carto-flow-vim.edn")

(def ^:private lock (Object.))

(defn manifest-decls
  "The RuntimeDecls this addon's manifest declares, read from the classpath."
  []
  (when-let [r (io/resource manifest-resource)]
    (vec (:addon/runtime (edn/read-string (slurp r))))))

(def host-record
  "A host's shared provisioner record, resolved at call time when that host is
   on the classpath: hive-mcp keeps one process-wide provisioner and exposes
   its `:installed` (addon id -> RuntimeDecls) here."
  'hive-mcp.extensions.runtime/installed)

(defn- record-fn
  [config]
  (or (:carto-flow.vim/installed config)
      (when-not (false? (:carto-flow.vim/host-record? config))
        (try (some-> (requiring-resolve host-record) deref)
             (catch Throwable _ nil)))))

(defn installed-decls
  "The decls whose installs to keep current. The provisioner's own record is
   the source: CONFIG's :carto-flow.vim/installed, a provisioner's `:installed`
   fn, else the host's shared one (`host-record`); exactly what it recorded for
   ADDON-ID is used. With no record available the decls are
   :carto-flow.vim/runtime-decls, else the manifest's, the ones the provisioner
   installs from; `provisioned?` still guards every install."
  [config addon-id]
  (if-let [installed (record-fn config)]
    (vec (get (installed) addon-id))
    (vec (or (:carto-flow.vim/runtime-decls config) (manifest-decls)))))

(defn home
  "CONFIG's :carto-flow.vim/home, else user.home, the provisioner's default."
  [config]
  (let [h (:carto-flow.vim/home config)]
    (if (and h (not (str/blank? (str h))))
      (str h)
      (System/getProperty "user.home"))))

(defn targets
  "[{:runtime/id :dir :loader}] for each decl the provisioner installs:
   where its install lives and the relative path of its generated loader,
   exactly as hive-addon.runtime.plan computes them."
  [config addon-id]
  (let [profiles (or (:carto-flow.vim/profiles config) plan/default-profiles)
        h (home config)]
    (vec (for [decl (installed-decls config addon-id)
               :let [profile (get profiles (:runtime/client decl))]
               :when profile]
           {:runtime/id (:runtime/id decl)
            :dir (plan/install-dir profile (:runtime/id decl) h)
            :loader (:profile/loader-path profile)}))))

(defn provisioned?
  "Whether DIR holds an install the provisioner made for runtime ID: a
   directory whose LOADER is the one hive-addon generates for that runtime."
  [dir loader id]
  (let [f (io/file dir loader)]
    (boolean
     (and (.isDirectory (io/file dir))
          (.isFile f)
          (str/includes? (first (str/split-lines (slurp f)))
                         (str "Generated by hive-addon for runtime " id))))))

(defn- ensure-parents!
  "Create the directories between the install root DIR and TARGET one level at
   a time, never DIR itself: when a deprovision removed DIR meanwhile, the
   first level fails instead of resurrecting the install."
  [^File dir ^File target]
  (let [root (.toPath dir)]
    (loop [p root
           [seg & more] (butlast (iterator-seq (.iterator (.relativize root (.toPath target)))))]
      (when seg
        (let [next-p (.resolve p seg)]
          (when-not (Files/isDirectory next-p (make-array java.nio.file.LinkOption 0))
            (Files/createDirectory next-p (make-array java.nio.file.attribute.FileAttribute 0)))
          (recur next-p more))))))

(defn- write-into-install!
  "Replace TARGET, below the install root DIR, with the bytes of SOURCE
   atomically (temp file in the same directory, then an atomic move)."
  [^File dir ^File source ^File target]
  (when-not (.isDirectory dir)
    (throw (ex-info "install removed during refresh" {:dir (str dir)})))
  (ensure-parents! dir target)
  (let [tmp (File/createTempFile (str "." (.getName target) ".") ".tmp" (.getParentFile target))]
    (try
      (Files/copy (.toPath source) (.toPath tmp)
                  ^"[Ljava.nio.file.CopyOption;"
                  (into-array [StandardCopyOption/REPLACE_EXISTING]))
      (Files/move (.toPath tmp) (.toPath target)
                  ^"[Ljava.nio.file.CopyOption;"
                  (into-array [StandardCopyOption/REPLACE_EXISTING
                               StandardCopyOption/ATOMIC_MOVE]))
      (finally (.delete tmp)))))

(defn- same-content?
  [^File a ^File b]
  (and (.isFile b)
       (= (.length a) (.length b))
       (java.util.Arrays/equals (Files/readAllBytes (.toPath a))
                                (Files/readAllBytes (.toPath b)))))

(defn refresh-install!
  "Bring one install up to SOURCE-DIR for the relative paths RELS, the files
   the provisioner copied from it. Returns {:runtime/id :dir :status s}
   with s :absent (no provisioned install, nothing done), :current, or
   :refreshed (with :written, the relative paths rewritten); or :error.
   Never throws."
  [source-dir rels {:keys [dir loader] id :runtime/id}]
  (let [report {:runtime/id id :dir dir}]
    (try
      (locking lock
        (if-not (provisioned? dir loader id)
          (assoc report :status :absent)
          (let [root (io/file dir)
                written (vec (for [rel rels
                                   :when (not= rel loader)
                                   :let [src (io/file source-dir rel)
                                         dst (io/file root rel)]
                                   :when (not (same-content? src dst))]
                               (do (write-into-install! root src dst) rel)))]
            (if (seq written)
              (assoc report :status :refreshed :written written)
              (assoc report :status :current)))))
      (catch Throwable t
        (assoc report :status :error :error (or (ex-message t) (str t)))))))

(defn refresh!
  "Refresh every provisioned install of ADDON-ID's runtimes from SOURCE-DIR,
   for the relative paths RELS. Returns {:trigger TRIGGER :at inst :installs
   [report ...]}. Never throws."
  [config addon-id source-dir rels trigger]
  {:trigger trigger
   :at (java.util.Date.)
   :installs (try
               (mapv #(refresh-install! source-dir rels %) (targets config addon-id))
               (catch Throwable t
                 [{:status :error :error (or (ex-message t) (str t))}]))})
